spring:
  jpa:
    properties:
      hibernate:
        dialect: PostgreSQLDialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  sql:
    init:
      mode: never
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${JDBC_DATABASE_PASSWORD:}
    username: ${JDBC_DATABASE_USERNAME:}

    url: ${JDBC_DATABASE_URL:}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: ${PORT:8080}
